#!/bin/bash
K=0
objdump -t -j *UND* build/libaseqmm.a | awk '{print $4}' | grep "^snd" > lib.txt
nm --defined-only -D /usr/lib/libasound.so | awk '{print $3}'| egrep "^snd_(seq|midi|timer)" |\
while read W; do
    grep -q $W lib.txt
    if [ "$?" != "0" ]; then
	let K++
	echo "$K $W"
    fi
done
rm -f lib.txt
