#!/bin/bash
if [ ! -d ../drumstick ]; then
    echo "Error: the directory ../drumstick doesn's exists. Checkout drumstick first."
    exit
fi
if [ -d drumstick ]; then
    echo "Error: the local directory drumstick already exists."
    exit
fi

mkdir -p drumstick/include
pushd drumstick/include
for F in ../../../drumstick/library/include/*.h; do
    ln -s $F .
done
popd

mkdir -p drumstick/src
pushd drumstick/src
for F in ../../../drumstick/library/src/*.cpp; do
    ln -s  $F .
done
popd

pushd drumstick
cat >CMakeLists.txt <<EOF
INCLUDE_DIRECTORIES(
    \${CMAKE_CURRENT_BINARY_DIR}
    \${CMAKE_CURRENT_SOURCE_DIR}/include
)

SET(drumstick_qtobject_SRCS
    include/alsaclient.h
    include/alsaevent.h
    include/alsaport.h
    include/alsaqueue.h
    include/alsatimer.h
    include/playthread.h
    include/qsmf.h
)

SET(drumstick_HEADERS
    include/alsaclient.h
    include/alsaevent.h
    include/alsaport.h
    include/alsaqueue.h
    include/alsatimer.h
    include/drumstickcommon.h
    include/playthread.h
    include/qsmf.h
    include/subscription.h
)

SET(drumstick_SRCS
    src/alsaclient.cpp
    src/alsaevent.cpp
    src/alsaport.cpp
    src/alsaqueue.cpp
    src/alsatimer.cpp
    src/playthread.cpp
    src/qsmf.cpp
    src/subscription.cpp
)

QT4_WRAP_CPP(drumstick_moc_SRCS \${drumstick_qtobject_SRCS})

ADD_LIBRARY(drumstick 
    \${drumstick_moc_SRCS}
    \${drumstick_SRCS} 
    \${drumstick_HEADERS} 
)

SET_TARGET_PROPERTIES(drumstick PROPERTIES COMPILE_FLAGS -fPIC)

TARGET_LINK_LIBRARIES(drumstick
    \${QT_LIBRARIES}
    \${ALSA_LIBS}
)
EOF
popd
