######################################################################
# Automatically generated by qmake (2.01a) sáb jul 26 13:55:12 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += smfplayer.h
FORMS += smfplayer.ui
SOURCES += main.cpp smfplayer.cpp
RESOURCES += smfplayer.qrc
