name: "Linux Build and Test"

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ${{github.workspace}}/DrumstickV2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -yq autoconf autoconf-archive automake libtool pkg-config libasound2-dev libpulse-dev

    - name: VCPKG Build
      uses: johnwason/vcpkg-action@v8
      id: vcpkg
      with:
        pkgs: zlib sonivox fluidsynth sndfile
        triplet: x64-linux-release
        token: ${{ github.token }}      
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.*'
        modules: qt5compat

    - name: Configure CMake
      run: cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_LOCATION}}
        -DUSE_FLUIDSYNTH=ON
        -DUSE_SONIVOX=ON
        -DUSE_PULSEAUDIO=ON
        -DBUILD_DOCS=OFF
        -DBUILD_UTILS=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -R "^(alsa|file|widgets)"

    - name: Install
      run: cmake --install ${{github.workspace}}/build

    - name: Create Archive
      run: |
        cd ${{github.workspace}}
        tar cvf DrumstickV2.tar DrumstickV2

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: DrumstickV2
        path: DrumstickV2.tar
        retention-days: 90
        overwrite: true
