name: "Linux CI"

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ${{github.workspace}}/DrumstickV2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "aarch64"]
        include:
          - { icon: '🟥', arch: "x86_64", os: "ubuntu-24.04", triplet: "x64-linux-release" }
          - { icon: '🟩', arch: "aarch64", os: "ubuntu-24.04-arm", triplet: "arm64-linux-release" }
    runs-on: ${{ matrix.os }}
    name: '${{ matrix.icon }} Linux ${{ matrix.arch }}'

    steps:
    - name: '${{ matrix.icon }} Checkout'
      uses: actions/checkout@v7

    - name: '${{ matrix.icon }} Dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -yq autoconf autoconf-archive automake libtool pkg-config libasound2-dev libpulse-dev libsndfile1-dev

    - name: '${{ matrix.icon }} Set up CMake'
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.3.x' # https://github.com/microsoft/vcpkg/issues/53135

    - name: '${{ matrix.icon }} VCPKG Build'
      uses: johnwason/vcpkg-action@v8
      id: vcpkg
      with:
        pkgs: zlib sonivox fluidsynth #[sndfile]fails in arm64, mpg123 should have: -DOPT_NEON=OFF, -DOPT_NEON64=OFF
        triplet: ${{ matrix.triplet }}
        token: ${{ github.token }}
        revision: master

    - name: '${{ matrix.icon }} Install Qt'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.1'
        modules: qt5compat

    - name: '${{ matrix.icon }} Configure CMake'
      run: cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_LOCATION}}
        -DUSE_FLUIDSYNTH=ON
        -DUSE_SONIVOX=ON
        -DUSE_PULSEAUDIO=ON
        -DBUILD_DOCS=OFF
        -DBUILD_UTILS=OFF

    - name: '${{ matrix.icon }} Build'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Test'
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -R "^(alsa|file|widgets)"

    - name: '${{ matrix.icon }} Install'
      run: cmake --install ${{github.workspace}}/build

    - name: '${{ matrix.icon }} Create Archive'
      run: |
        cd ${{github.workspace}}
        tar cvzf DrumstickV2-${{ matrix.arch }}.tar.gz DrumstickV2

    - name: '${{ matrix.icon }} Upload Artifacts'
      uses: actions/upload-artifact@v7
      with:
        name: DrumstickV2-${{ matrix.arch }}
        path: DrumstickV2-${{ matrix.arch }}.tar.gz
        retention-days: 90
        overwrite: true
        archive: false
