name: macOS CI

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: DrumstickV2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "aarch64"]
        include:
          - { arch: "x86_64", os: "macos-15-intel"  }
          - { arch: "aarch64", os: "macos-15" }
    runs-on: ${{ matrix.os }}
    name: 'macOS ${{ matrix.arch }}'

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: 'Clone vcpkg-custom-triplets repository'
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'master'
        owner: 'pedrolcl'
        repository: 'vcpkg-custom-triplets'

    - name: 'Set up CMake'
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.4.x' # https://github.com/microsoft/vcpkg/issues/53135

    - name: 'VCPKG Build'
      uses: johnwason/vcpkg-action@v8
      id: vcpkg
      with:
        pkgs: fluidsynth #[sndfile] fails because mpg123 still uses autotools
        triplet: universal-osx
        token: ${{ github.token }}
        revision: master        
        extra-args: --overlay-triplets=${{ github.workspace }}/vcpkg-custom-triplets

    - name: 'Install Qt'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        modules: qt5compat

    - name: 'Configure CMake'
      run: >
        cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_LOCATION}}
        -DCMAKE_OSX_DEPLOYMENT_TARGET="12.0"
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
        -DCMAKE_INSTALL_RPATH="@executable_path/../Frameworks"
        -DBUILD_FRAMEWORKS=ON
        -DBUILD_DOCS=OFF
        -DBUILD_UTILS=ON
        -DUSE_QT5=OFF
        -DUSE_FLUIDSYNTH=ON
        -DUSE_SONIVOX=OFF
        -DUSE_PULSEAUDIO=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Install
      run: cmake --install ${{github.workspace}}/build

    - name: 'Create Archive'
      run: |
        cd ${{github.workspace}}
        tar cvzf ${{env.INSTALL_LOCATION}}-universal-macos.tar.gz ${{env.INSTALL_LOCATION}}

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.INSTALL_LOCATION}}-${{ matrix.arch }}-macos
        path: ${{env.INSTALL_LOCATION}}-${{ matrix.arch }}-macos.tar.gz
        retention-days: 90
        overwrite: true
        archive: false
